### ISSUE TITLE
mypmpro.ps1 missing ?

### ISSUE THREAD

**Issue by Tpaquot** [mbegan/PMPro-PSModule#1]
Hi there, 
We have Password Management Pro and this module would be really interresting if it eases the process of getting password out of PMP. 
Would it be possible to have some examples to illustrate this module ?
Regards

**Comment by mbegan** [comment]
Hi @Tpaquot, i never made it very far in building this module.  Since starting I have changed roles and companies and no longer have access to a pmp instance to event test with, sorry.
